[package]
name = "db-util"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
casper-hashing = "1.4.3"
casper-node = "1.4.5"
casper-types = "1.5.0"
clap = "3.1.17"
lmdb = "0.8.0"
lmdb-sys = "0.8.0"
log = "0.4.17"
serde = {version = "1", features = ["derive"] }
simplelog = "0.12.0"
thiserror = "1.0.31"

[dev-dependencies]
rand = "0.8.5"
tempfile = "3.3.0"
